# Generated by Django 4.1.7 on 2023-04-24 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arcaledapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam', to='arcaledapp.lesson'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson', to='arcaledapp.branch'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson', to='arcaledapp.teacher'),
        ),
    ]
